### PR TITLE
fix: Recreated the profile page

### PR DESCRIPTION
**Pull request by Luqman07**
I deleted the previous FE page that worked on it and recreated it

### CODE REVIEW

**Review by lerderl — COMMENTED** [review]
Please pull dev and rebase once more before pushing to your remote branch again

**Comment by Luqman07** [comment]
I have two PR's, Should I do that for the dashboard as well?

**Comment by Luqman07** [comment]
Done @lerderl

**Review by lerderl — APPROVED** [review]
Good job

**Pull request merged**
